name: Github Actions
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Building:
    name: Build hw solution
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building
        run: |
          ./scripts/build.sh
          cd build
          make
  Formating:
    name: Automatic formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checking coding style
        run: |
          ./scripts/clang-formating.sh
  Linters:
    name: Running linters check
    runs-on: ubuntu-latest
    needs: Formating
    steps:
      - uses: actions/checkout@v2
      - name: Run linters checks
        run: |
          ./scripts/build.sh
          ./scripts/linters.sh
#  Testing:
#    name: Running testing check
#    runs-on: ubuntu-latest
#    needs: Linters
#    steps:
#      - uses: actions/checkout@v2
#      - name: Run testing check
#        run: |
  Coverage:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    needs: Linters
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install gcovr
          gcovr -r . -e ".*_deps.*||.*tests.*|project/main.c" -o coverage --xml
      - uses: codecov/codecov-action@v2
        with:
          token: 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
          files: ./coverage.xml
          flags: unittests
          name: coverage_
          fail_ci_if_error: true
          verbose: true